import React from 'react'; import ReactDOM from 'react-dom/client'; import { Toaster, toast } from 'react-hot-toast'; import './styles/index.css'
import { Database, LogOut } from 'lucide-react'

function App(){
  const [defaults,setDefaults]=React.useState<any>(); const [conn,setConn]=React.useState<any>(); const [dbs,setDbs]=React.useState<string[]>([])
  const [server,setServer]=React.useState(''); const [authMode,setAuthMode]=React.useState<'windows'|'sql'>('windows'); const [username,setUsername]=React.useState(''); const [password,setPassword]=React.useState('')
  const [selectedDb,setSelectedDb]=React.useState(''); const [folder,setFolder]=React.useState(''); const [bak,setBak]=React.useState(''); const [target,setTarget]=React.useState('')
  React.useEffect(()=>{window.safebridge.defaults().then((d)=>{setDefaults(d);setServer(d.serverCandidates[0]);setFolder(d.backupDir)})},[])
  const doConnect=async()=>{const payload={server,authMode,username,password}; try{const res=await window.safebridge.connect(payload); setConn(payload); setDbs(res.databases); toast.success('Bienvenido a SafeBridge')}catch(e:any){toast.error(e.message)}}
  if(!conn) return <div className='min-h-screen grid place-items-center p-8'><Toaster/><div className='card w-full max-w-xl space-y-4'><div className='h-24 border-2 border-dashed border-cyan-500/60 rounded-xl grid place-items-center'>Logo SafeBridge</div><p>Equipo detectado: <b>{defaults?.host}</b></p><input className='input' value={server} onChange={e=>setServer(e.target.value)} placeholder='Servidor'/><div className='flex gap-2'><button className={`btn ${authMode==='windows'?'':'opacity-60'}`} onClick={()=>setAuthMode('windows')}>Autenticación Windows</button><button className='btn' onClick={()=>setAuthMode('sql')}>Autenticación SQL Server</button></div>{authMode==='sql'&&<><input className='input' placeholder='Usuario' value={username} onChange={e=>setUsername(e.target.value)}/><input className='input' type='password' placeholder='Contraseña' value={password} onChange={e=>setPassword(e.target.value)}/></>}<button className='btn w-full' onClick={doConnect}>Conectar</button></div></div>
  const runBackup=async()=>{if(!selectedDb)return toast.error('Selecciona una base'); const res=await window.safebridge.runBackup(conn,selectedDb,folder,false); if(res.exists){if(confirm('Ya existe backup con ese nombre. ¿Sobrescribir?')) await window.safebridge.runBackup(conn,selectedDb,folder,true); else return;} toast.success('Backup + validación completados')}
  const runRestore=async()=>{if(!bak||!target)return toast.error('Selecciona .bak y destino'); if(!confirm('¿Confirmas restaurar backup?')) return; const res=await window.safebridge.runRestore(conn,bak,target,false); if(res.conflict){if(confirm('La BD existe. ¿Forzar sobrescritura?')) await window.safebridge.runRestore(conn,bak,target,true)} toast.success('Restauración ejecutada')}
  return <div className='p-6 space-y-6'><Toaster/><header className='card flex justify-between items-center'><div className='flex items-center gap-2'><Database className='text-cyan-400'/><h1 className='text-xl font-bold'>SafeBridge</h1></div><div className='flex items-center gap-4'><span>Conectado: {conn.username||'Windows'}@{conn.server}</span><button className='btn' onClick={()=>setConn(null)}><LogOut size={16}/></button></div></header><main className='grid md:grid-cols-2 gap-6'><section className='card space-y-3'><h2 className='font-semibold'>Generar Backup + Validación</h2><select className='input' value={selectedDb} onChange={e=>setSelectedDb(e.target.value)}><option value=''>Selecciona BD</option>{dbs.map(d=><option key={d} value={d}>{d}</option>)}</select><div className='flex gap-2'><input className='input' value={folder} readOnly/><button className='btn' onClick={async()=>{const f=await window.safebridge.pickFolder(); if(f) setFolder(f)}}>Buscar carpeta...</button></div><button className='btn w-full' onClick={runBackup}>Ejecutar Backup + Validación</button></section><section className='card space-y-3'><h2 className='font-semibold'>Restaurar desde .bak</h2><div className='flex gap-2'><input className='input' value={bak} readOnly/><button className='btn' onClick={async()=>{const f=await window.safebridge.pickBak(); if(f) setBak(f)}}>Seleccionar archivo .bak</button></div><input className='input' placeholder='Base de datos destino' value={target} onChange={e=>setTarget(e.target.value)}/><button className='btn w-full' onClick={runRestore}>Restaurar Backup</button></section></main></div>
}
ReactDOM.createRoot(document.getElementById('root')!).render(<App />)
